### ISSUE TITLE
Failure to import Thief Racket

### ISSUE THREAD

**Issue by brandon-kohn** [zarmstrong/foundry-pathbuilder2e-import#12]
Whenever I try to import a character who is a 4th level thief with the Thief Racket, the import fails.

**Comment by brandon-kohn** [comment]
[thief.zip](https://github.com/zarmstrong/foundry-pathbuilder2e-import/files/7847426/thief.zip)
Here is the json.

**Comment by brandon-kohn** [comment]
After investigation, it seems to be an issue with the Soap item from a Rogue's Kit. When I remove the soap it works.

**Comment by zarmstrong** [comment]
What versions of everything?
