### ISSUE TITLE
Both .js files just hold "not compatible with v9" alert code & manifest not pointing to a valid download.

### ISSUE THREAD

**Issue by tehguitarist** [zarmstrong/foundry-pathbuilder2e-import#21]
Subject says it all really.
There are also some issues with the module.json throwing up deprecation errors, I'll do up a PR for that if I get some time this week, but they should be quite straightforward to fix.

**Comment by zarmstrong** [comment]
thanks checking into it

**Comment by zarmstrong** [comment]
fixed in v0.10.1.
