### ISSUE TITLE
Background and Deity Don't Import Correctly

### ISSUE THREAD

**Issue by nrllewellyn** [zarmstrong/foundry-pathbuilder2e-import#3]
(Issues are disabled on the @zarmstrong fork, so hopefully this is the correct place to post issues!)

Background doesn't import from the "Build" page.

Example character: 107055

Tested with:
Foundry: 0.8.8
Pathbuilder 2e Importer: 0.6.2

**Comment by zarmstrong** [comment]
I tested importing 107055 and pathbuilder versions 0.6.1 and 0.6.4 running on 0.8.8 and background imported properly, along with the BG skill feat. The only thing I noticed that was incorrect was it didn't put the BG skill in the right slot.

![image](https://user-images.githubusercontent.com/565269/126927790-0318617b-557b-4405-b32b-234de4b39281.png)
![image](https://user-images.githubusercontent.com/565269/126927823-ad6fc8e3-ee16-4040-a6d8-c31c34923477.png)

**Comment by zarmstrong** [comment]
Deity is now imported in v.0.6.5 1ccf385

**Comment by zarmstrong** [comment]
This was fixed a while ago.
