### ISSUE TITLE
Imported characters' cantrips deal 1 to many dice of damage.

### ISSUE THREAD

**Issue by Bolt7** [zarmstrong/foundry-pathbuilder2e-import#6]
Steps to reproduce:
- Import character with damage-dealing cantrip
- roll the cantrip's damage from the spell card in chat

**Comment by bennyty** [comment]
Looks like this is not a problem anymore. My Oracle's `Chill Touch` `Divine Lance`, Summoner's `Produce Flame` are working for me.
