### ISSUE TITLE
Issue with Armor Class import

### ISSUE THREAD

**Issue by Doctor-Unspeakable** [zarmstrong/foundry-pathbuilder2e-import#7]
Hi Zach,

Apparently there is an issue with the armor class import, someone posted about it here:

https://www.reddit.com/r/Pathfinder2e/comments/q4dxfn/foundry_pathfinder_2e_module_update_messed_up_acs/

Thanks!

Dave

**Comment by zarmstrong** [comment]
I think this was fixed a while back. Either way, it's not currently relevant so I'll close this out for now.
